services:
  - type: web
    name: lms-dashboard
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: MOODLE_BASE_URL
        sync: false
      - key: MOODLE_TOKEN
        sync: false
      - key: SYNC_SECRET
        sync: false
      - key: KESHER_USERNAME
        sync: false
      - key: KESHER_PASSWORD
        sync: false
      - key: KESHER_PAYMENT_PAGE_ID
        value: "325869"
      - key: YAHAV_CLIENT_CODE
        value: "2270"
      - key: YAHAV_ORIGIN_CITY
        value: "בני ברק"
      - key: YAHAV_ORIGIN_STREET
        value: "מגדלי הכשרת היישוב ז'בוטינסקי"
      - key: YAHAV_ORIGIN_STREET_NUM
        value: "9"
      - key: YAHAV_ORIGIN_COMPANY
        value: "למען ילמדו"
      - key: DHL_API_KEY
        sync: false
      - key: DHL_API_SECRET
        sync: false
      - key: DHL_ACCOUNT_NUMBER
        sync: false
      - key: DHL_BASE_URL
        value: "https://express.api.dhl.com/mydhlapi/test"
      - key: DHL_SHIPPER_EMAIL
        sync: false
